name: todo_list_get_x
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  equatable: ^2.0.5
  get: 4.6.5
  flutter_easyloading: ^3.0.5
  flutter: 
    sdk: flutter
  step_progress_indicator: ^1.0.2
  dotted_border: ^2.0.0+3

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/


